# Numpy introduction #
### What is Numpy ###
**Numpy** is a Python **package** :
- It has been created for **scientific computing**
- It helps handle large **multidimensional arrays** and **matrices**
- usefull for **high-level mathematical functions**

### Import numpy

In [2]:
import numpy as np

### Creating two arrays

In [3]:
n1_array = np.array([[0,1,2,3],[4,5,6,7]])
n2_array = np.array([[1,2,3,4],[2,5,6,8]])

## l. Some Numpy arrays attribute

### 1) The number of dimensions##

In [4]:
n1_array.ndim

2

**==> The number of dimensions is 2, n1_array is an 2D array**

### 2) The number of elements of the array

In [5]:
n1_array.size

8

**==> n1_array have 8 elements**

### 3) The size of each dimension

In [6]:
n1_array.shape

(2, 4)

**==> n1_array have 2 rows and 4 columns**

### 4) The type of the elements 

In [8]:
n1_array.dtype.name

'int32'

In [9]:
n1_array.dtype

dtype('int32')

**==> All the elements of n1_array are integers**   


***

## ll. Mathematical operation

### 1) Arrays substraction ##

In [11]:
n3_array = n1_array - n2_array
n3_array

array([[-1, -1, -1, -1],
       [ 2,  0,  0, -1]])

==> The substraction happens *element by element*  
> Do note that when you substract **2 arrays**, they should be of **equal dimensions**

### 2) Squaring 

In [12]:
n3_array**2

array([[1, 1, 1, 1],
       [4, 0, 0, 1]], dtype=int32)

### 3) Trigonometric function 

#### Cosinus

In [14]:
np.cos(n3_array)


array([[ 0.54030231,  0.54030231,  0.54030231,  0.54030231],
       [-0.41614684,  1.        ,  1.        ,  0.54030231]])

#### Sinus 

In [15]:
np.sin(n3_array)

array([[-0.84147098, -0.84147098, -0.84147098, -0.84147098],
       [ 0.90929743,  0.        ,  0.        , -0.84147098]])

#### Tangente

In [16]:
np.tan(n3_array)

array([[-1.55740772, -1.55740772, -1.55740772, -1.55740772],
       [-2.18503986,  0.        ,  0.        , -1.55740772]])

### 4) Conditional operation 

In [19]:
n1_array < 2

array([[ True,  True, False, False],
       [False, False, False, False]])

In [20]:
n2_array > 5

array([[False, False, False, False],
       [False, False,  True,  True]])

### 4) Matrix multiplication 

In [28]:
A1 = np.array([[1, 2],
             [0, 2]])
A2 =np.array([[4, 3],
             [2, 1]])

#### Element by element multiplication 

In [29]:
A1*A2

array([[4, 6],
       [0, 2]])

#### Dot product 
Horizontal elements (=) x Vertical elements (||)

In [30]:
np.dot(A1,A2)

array([[8, 5],
       [4, 2]])

---

## lll. Indexing and Slicing

### 1) Select one or many elements

In [32]:
n_array= np.array([[4,5,6],['a','z','t']])

In [36]:
n_array[1,2]

't'

==> We have selected the **third** element *`'t'`* (*second dimension or column*) from the **second element** *`['a','z','t']`* (*first dimension or row*)   

In [37]:
n_array[0,0:]

array(['4', '5', '6'], dtype='<U11')

==> Here we said : Python select from the **first row/dimension**, the element/values from **position zero** to the **last one** by `0:`

In [39]:
n_array[0,0:2]

array(['4', '5'], dtype='<U11')

==> Here we said : Python from the **first row/dimension**, select the values from **position zero** '4' to the **first one** '5' by `0:2`

In [40]:
n_array[:,0]

array(['4', 'a'], dtype='<U11')

==> Here we said : Python select from **all** the rows(first dimension elements), the **first** values of columns